branches:
  only: 
    - master
    - release
    - develop
sudo: false
language: ruby
rvm:
    - 1.8.7
    - 1.9.3
    - 2.0.0
    - 2.1.0
    - 2.2.0
    - 2.3.0
    - 2.4.0
before_install: gem install bundler -v 1.11.2
cache:
  directories:
    - vendor/bundle
install: bundle install --path=vendor/bundle
script:
    - ruby --version
    - bundle exec rake spec
